autoload :Noteboostnote,        'boostnote/note'
autoload :NoteBoostSnippet,     'boostnote/note'
autoload :FolderBoostNoteRoot,  'boostnote/folder'
autoload :FolderBoostNote,      'boostnote/folder'
autoload :LocationBoostNote,    'boostnote/location'
